import os
import sys
import subprocess

def check_dependencies():
    """Check if all dependencies are installed."""
    try:
        # Try importing required packages
        import pandas
        import numpy
        import dash
        import dash_bootstrap_components
        import plotly
        import tensorflow
        import sklearn
        print("✅ All dependencies are installed.")
        return True
    except ImportError as e:
        print(f"❌ Missing dependency: {e}")
        return False

def generate_sample_data():
    """Generate sample data for testing if it doesn't exist."""
    if not os.path.exists('data'):
        os.makedirs('data', exist_ok=True)
        
    # Check if we have any sample data files
    sample_files = [f for f in os.listdir('data') if f.endswith('.xlsx')]
    
    if not sample_files:
        print("Generating sample data files...")
        try:
            from data.sample_stock_data import generate_sample_stock_data
            # Sample data will be generated by importing the module
            print("✅ Sample data generated successfully.")
        except Exception as e:
            print(f"❌ Error generating sample data: {e}")
            # Create a basic sample file if the generator fails
            try:
                import pandas as pd
                import numpy as np
                from datetime import datetime, timedelta
                
                # Generate a simple dataset
                dates = [datetime.now() - timedelta(days=i) for i in range(500, 0, -1)]
                close = np.random.normal(1000, 50, 500).cumsum() + 1000
                
                # Create a DataFrame
                df = pd.DataFrame({
                    'Date': dates,
                    'Open': close * np.random.uniform(0.99, 1.01, 500),
                    'High': close * np.random.uniform(1.01, 1.03, 500),
                    'Low': close * np.random.uniform(0.97, 0.99, 500),
                    'Close': close,
                    'Volume': np.random.randint(1000, 10000, 500)
                })
                
                # Save to file
                df.to_excel('data/sample_stock_data.xlsx', index=False)
                print("✅ Basic sample data created.")
            except Exception as e:
                print(f"❌ Could not create sample data: {e}")

def create_required_directories():
    """Create required directories if they don't exist."""
    directories = ['data', 'output', 'models']
    for directory in directories:
        os.makedirs(directory, exist_ok=True)
    print("✅ Required directories created.")

def run_app():
    """Run the application."""
    try:
        import app
        print("Starting Stocks AI application...")
        print("Open your browser at http://127.0.0.1:8050/ to access the app")
        app.app.run_server(debug=True)
    except Exception as e:
        print(f"❌ Error running the application: {e}")
        sys.exit(1)

if __name__ == "__main__":
    print("=" * 50)
    print("Stocks AI - NEPSE Market Prediction Setup")
    print("=" * 50)
    
    # Check dependencies
    if not check_dependencies():
        print("\nInstalling dependencies...")
        subprocess.run([sys.executable, '-m', 'pip', 'install', '-r', 'requirements.txt'])
    
    # Create required directories
    create_required_directories()
    
    # Generate sample data
    generate_sample_data()
    
    print("\nSetup complete! Starting application...\n")
    
    # Run the application
    run_app() 